### ISSUE TITLE
erroneous Java UTF8 string creation

### ISSUE THREAD

**Issue by hneemann** [Herbert-Karl/digital-asm#3]
This implementation leads to an invalid transmission as soon as the string length exceeds 127 bytes.

https://github.com/Herbert-Karl/digital-asm/blob/e2b4bbb1df9e474499b923822cb7e6f009321ce4/src/remoteInterface.ts#L115

**Comment by Herbert-Karl** [comment]
found and fixed the Problem
for a value larger then 127 in either high or low, the Byte was converted into two Bytes in the resulting string, thereby creating a wrongly formated message
